# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "mpt3sas"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [
    "kvm-amd"
    "wl"
  ];
  # insecure and wireless is not used
  # boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c9b07de5-8509-43a9-add8-912d66be0ea8";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CC5E-3F02";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # TODO: mordor/data currently inherits recordsize=1M and sync=disabled from mordor.
  # This is problematic for SQLite databases (e.g. Jellyfin at /srv/data/jellyfin):
  #   - recordsize=1M causes 256x write amplification on 4K SQLite pages (read-modify-write)
  #   - sync=disabled means fsync is ignored, risking DB corruption on power loss
  # Fix: create a child dataset for database workloads:
  #   zfs create -o recordsize=8K -o sync=standard -o compression=zstd mordor/data/jellyfin-db
  # Or if changing mordor/data directly, note recordsize only applies to newly written blocks —
  # existing files must be copied in-place (cp + mv) to rewrite at the new recordsize.
  fileSystems."/srv/data" = {
    device = "mordor/data";
    fsType = "zfs";
  };

  fileSystems."/srv/vault" = {
    device = "mordor/vault";
    # fix age secrets not available to services (sometimes)
    # https://github.com/ryantm/agenix/issues/45#issuecomment-958146520
    neededForBoot = true;
    fsType = "zfs";
  };

  fileSystems."/srv/share/emma" = {
    device = "mordor/share/emma";
    fsType = "zfs";
  };

  fileSystems."/srv/share/public" = {
    device = "mordor/share/public";
    fsType = "zfs";
  };

  fileSystems."/srv/media" = {
    device = "mordor/media";
    fsType = "zfs";
  };

  fileSystems."/srv/share/sam" = {
    device = "mordor/share/sam";
    fsType = "zfs";
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 32 * 1024; # 32 GB
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.podman0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp97s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
